### ISSUE TITLE
Deploy to ZEIT Now?

### ISSUE THREAD

**Issue by coetry** [jasminmif/react-interactive-paycard#8]
Hey! This is a really cool! It would be amazing to see it deployed on something like ZEIT so that people can interact with it live! In fact, we have it deployed right here: https://react-interactive-paycard.now.sh/

You can deploy this particular project with the following link: https://zeit.co/new/project?template=https://github.com/jasminmif/react-interactive-paycard

Once you get your ZEIT project connected to your GitHub repo, as community members send you PRs, you get a URL where you can inspect a deployed version of the PR before merging to master 🚀 .

**Comment by chintan9** [comment]
I have pr for that https://github.com/jasminmif/react-interactive-paycard/pull/13
